### PR TITLE
Enable the user to set the encoding

### PR DESCRIPTION
**Pull request by Jadiker**
I was running into issues where the parser couldn't decode a byte. Most files will use a utf8 encoding, so this should work for most files. Feel free to change the default; I just need the ability to set the encoding.

### CODE REVIEW

**Comment by Yevgnen** [comment]
Hi, thanks for the PR. Should we also add the default `encoding` param to `parse` method and pass it through `_parse_text` and `_parse_ann` as default? How do you think?

**Comment by Jadiker** [comment]
Sorry for just seeing this comment now! Yeah, what you did makes a lot more sense!

**Comment by Jadiker** [comment]
Just re-opening for merge.

**Comment by Yevgnen** [comment]
Thanks!

**Pull request merged**
